
theme: jekyll-theme-leap-day

title: "Innovations and Opportunities in Liberal Arts Computing Education"
description: "SIGCSE 2022 Affiliated Event by the SIGCSE Committee on Computing Education in Liberal Arts Colleges"
